apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-nap
  name: nginx-nap
spec:
  tolerations:
  - key: app
    operator: Equal
    value: finance
    effect: NoSchedule
  nodeSelector:
    app: finance
  containers:
  - image: nginx
    name: nginx-nap
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi      
  restartPolicy: Always
