apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-pool-1
  name: nginx-pool-1
spec:
  nodeSelector:
    pool-name: gke-pool-1
  containers:
  - image: nginx
    name: nginx-pool-1
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi      
  restartPolicy: Always
